on:
  push:
  pull_request:
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
    - name: echo string
      run: echo "string"
    - name: multi line string
      run: |
        pwd
        ls -a

